version: "3.5"

services:
  app:
    build: .
    container_name: edushield
    restart: unless-stopped
    networks:
      - default
      - itskdhere
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    volumes:
      - ./firebaseServiceAccountKey.json:/app/firebaseServiceAccountKey.json:ro

networks:
  itskdhere:
    external: true
    name: itskdhere
