version: "3.5"

services:
  app:
    build: .
    container_name: edushield
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env
    ports:
      - $PORT:$PORT

networks:
  default:
    external: true
    name: itskdhere
